# Generated by Django 4.2 on 2023-04-08 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technological_skills',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traning_module',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=254, null=True)),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='women_in_tech.technological_skills')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('mentor_name', models.CharField(blank=True, max_length=254, null=True)),
                ('mentor_email', models.EmailField(max_length=254, unique=True)),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='women_in_tech.technological_skills')),
            ],
        ),
    ]
