# Generated by Django 4.2 on 2023-04-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliable_jobs',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(blank=True, max_length=254, null=True)),
                ('job_description', models.TextField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('full time', 'full time'), ('part time', 'part time')], max_length=254, null=True)),
                ('salary', models.IntegerField()),
                ('kind_of_support', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
